### ISSUE TITLE
MCP73831 PROG resistor

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/labwiz-board#57]
Check the PROG resistor on the battery charger. Make sure the value defines the correct charge rate.

**Comment by samchoy88** [comment]
Since we face the same issue in T400 circuit design.
https://github.com/PaxInstruments/t400-electronics/issues/163

We should follow the T400 electronic design and use 2.32K (1%) in here
With a 2.32K resistor the typical charge current would be 1000 / 2.32 = 431mA
The highest and lowest possible charge currents, using 10% for the chip and 1% for the resistor would be:
Maximum 479mA
Minimum 384mA

![image](https://cloud.githubusercontent.com/assets/1327611/7234227/172bdc14-e7b8-11e4-962c-c9c4497582ba.png)

**Comment by charlespax** [comment]
I've added a 2.32K resistor to the RLC library and added it to the schematic.

![screen shot 2016-12-11 at 12 46 09](https://cloud.githubusercontent.com/assets/281642/21078390/dcf43886-bf9f-11e6-8d33-e03cd7127f46.png)
